name: SimpleAuth
version: '${project.version}'
main: me.irinque.simpleauth.Main
authors: [irinque]
api-version: '1.20'
commands:
  register:
    aliases:
      - r
      - reg
    usage: /<command> <password>
  login:
    aliases:
      - l
      - log
    usage: /<command> <password>
  reload-simpleauth:

