name: SimpleAuth
version: '1.0.3'
main: me.irinque.simpleauth.SimpleAuth
api-version: '1.19'
authors: [ irinque ]
website: https://github.com/irinque
commands:
  register:
    aliases:
      - r
      - reg
    usage: /<command> <password>
    description: Register command
  login:
    aliases:
      - l
      - log
    usage: /<command> <password>
    description: Login command
  changepassword:
    aliases:
      - cp
    usage: /<command> <old_password> <new_password>
    description: Changes password
  simpleauth:
    aliases:
      - sa
    description: Admin command
